### PR TITLE
Parse string based descriptions

### LINKED ISSUE #147: Support latest syntax for descriptions
Descriptions in schemas are now represented as strings instead of comments as of [graphql-js 0.12.0](https://github.com/graphql/graphql-js/releases/tag/v0.12.0)
https://github.com/graphql/graphql-js/pull/927

### LINKED ISSUE #196: Support for string literals as description
As of version 0.12.3 the default style of describing a type or field is to add a string literal instead of a comment.
https://github.com/graphql/graphql-js/blob/master/src/utilities/extendSchema.js#L44

Using the schema
```graphql
"This is a description."
schema {
    query: Query
}
```
results in a crash.

### PR DESCRIPTION
**Pull request by gracenoah**
This implementation is probably lax about where string descriptions are allowed. Additional test cases would be needed to verify the accuracy of the implementation. Also, this is backwards compatible with comment based descriptions and there's an option to disable the backwards compatibility.

fix #196 
fix #147

### CODE REVIEW

**Comment by pavelnikolov** [comment]
Thank you for your PR! I'll review it shortly!

**Comment by gracenoah** [comment]
Thinking about this PR again this morning, I realize it's a real quick and dirty fix that works for my current use case, but in general is way too permissive. I'm thinking of improving it by splitting up Consume() from ConsumeDescription() instead of having a flag passed into the same function that consumes either one. That way I can significantly reduce the possible invalid schemas accepted. I think I was trying too hard to keep my changes only within the Consume() function and that led to a bad design. Feel free to review other PRs first. I'll let you know when I think this is in a mergable state.

**Comment by gracenoah** [comment]
Updated. I think this is a bit more reasonable. I'm still not happy with the level of testing, but it did work with the new flag on in our codebase.

File: graphql.go [hunk 1]
```diff
@@ -34,7 +34,7 @@ func ParseSchema(schemaString string, resolver interface{}, opts ...SchemaOpt) (
 		opt(s)
 	}
 
-	if err := s.schema.Parse(schemaString); err != nil {
+	if err := s.schema.Parse(schemaString, s.noCommentsAsDescriptions); err != nil {
```
Comment (pavelnikolov) [inline graphql.go]: Should we name the variable `useStringComments` instead? I think that shorter is better. WDYT?

**Comment by Arachnid** [comment]
Is there anything preventing this from being merged? It'd be great to be able to load schemas with documentation in them.

**Comment by pavelnikolov** [comment]
@Arachnid I'm sorry for the delay. I'm currently looking into subscriptions and then I'll get back to the remaining PRs - I think that tis name (i.e. `noCommentsAsDescriptions`) is too long. Otherwise, LGTM.

File: graphql.go (hunk 1 above)
Comment (gracenoah) [reply graphql.go]: I'll rename it to useStringsAsDescriptions. The spec uses the term "description" so I prefer to use that here too.

Comment (gracenoah) [reply graphql.go]: Actually, `useStringDescriptions` is as short as I can make it.

**Comment by gracenoah** [comment]
Ready to merge if you are happy with it.

File: internal/common/lexer.go [hunk 2]
```diff
@@ -132,19 +166,57 @@ func (l *Lexer) Location() errors.Location {
...
+func (l *Lexer) consumeTripleQuoteComment() {
+	if l.next != '"' {
+		panic("consumeTripleQuoteComment used in wrong context: no third quote?")
+	}
+
+	if l.descComment != "" {
+		l.descComment += "\n"
+	}
+
+	comment := ""
```
Comment (pavelnikolov) [inline internal/common/lexer.go]: I would prefer using the default value here instead of using an assignment:
```go
var comment string
```

File: internal/common/lexer.go [hunk 3]
```diff
@@ -132,19 +166,57 @@ func (l *Lexer) Location() errors.Location {
...
+	numQuotes := 0
```
Comment (pavelnikolov) [inline internal/common/lexer.go]: default val again:
```go
var numQuotes int
```

File: internal/common/lexer.go [hunk 4]
```diff
@@ -84,6 +88,31 @@ func (l *Lexer) Consume() {
...
+		if l.sc.Peek() == '"' {
+			// Consume the third quote
+			l.next = l.sc.Next()
+			l.consumeTripleQuoteComment()
+		} else {
+			l.consumeStringComment(tokenText)
+		}
+		return true
+	}
+	return false
```
Comment (pavelnikolov) [inline internal/common/lexer.go]: This line is not covered by unit tests...

File: internal/common/lexer.go [hunk 5]
```diff
@@ -132,19 +166,57 @@ func (l *Lexer) Location() errors.Location {
 	}
 }
 
+func (l *Lexer) consumeTripleQuoteComment() {
+	if l.next != '"' {
+		panic("consumeTripleQuoteComment used in wrong context: no third quote?")
+	}
+
+	if l.descComment != "" {
+		l.descComment += "\n"
```
Comment (pavelnikolov) [inline internal/common/lexer.go]: Not covered by unit tests. Can you add a case for this, please?

File: internal/common/lexer.go [hunk 6]
```diff
@@ -132,19 +166,57 @@ func (l *Lexer) Location() errors.Location {
...
+		if numQuotes == 3 || l.next == scanner.EOF {
+			break
+		}
+	}
+	l.descComment += strings.TrimSpace(comment[:len(comment)-numQuotes])
+}
+
+func (l *Lexer) consumeStringComment(str string) {
+	if l.descComment != "" {
+		l.descComment += "\n"
```
Comment (pavelnikolov) [inline internal/common/lexer.go]: Not covered by unit tests. Can you add a test case for this, please?

File: graphql.go [hunk 7]
```diff
@@ -63,16 +63,24 @@ type Schema struct {
...
+	tracer                trace.Tracer
+	validationTracer      trace.ValidationTracer
+	logger                log.Logger
+	useStringDescriptions bool
 }
 
 // SchemaOpt is an option to pass to ParseSchema or MustParseSchema.
 type SchemaOpt func(*Schema)
 
+// UseStringDescriptions disables the parsing of comments as descriptions
```
Comment (pavelnikolov) [inline graphql.go]: Can you make this comment a little bit more descriptive, please? This comment will be used by `godoc` to generate documentation for the library and some users might not even know about strings vs comments as descriptions.

**Comment by gracenoah** [comment]
Sorry I haven't been responsive. I think I'll be able to get back to this next week.

File: internal/common/lexer.go (hunk 6 above)
Comment (gracenoah) [reply internal/common/lexer.go]: Actually this case doesn't make sense. A one line string comment will always be the only description.

**Comment by gracenoah** [comment]
updated
