### PR TITLE
Fixed duplicated __typename in response (fixes #369)

### LINKED ISSUE #369: __typename not merged
When i start server with `go run example/starwars/server/server.go` and execute this query : 
```
query TestMerge {
  hero {
    __typename
    name
    
    ... on Character {
      ...Droid
      name
      __typename
    }
    
  }
}

fragment Droid on Droid {
  name
  __typename
}
```

GraphiQL merge __typename field but the server response has multiple __typename.
Result with server response (browser network inspect) : 
```
{"data":{"hero":{"__typename":"Droid","name":"R2-D2","__typename":"Droid","__typename":"Droid"}}}
```

Expected : 
```
{"data":{"hero":{"name":"R2-D2","__typename":"Droid"}}}
```
With graphql-js __typename is merged.

link #365

### PR DESCRIPTION
**Pull request by eko**
This pull request fixes issue reported in #369

### CODE REVIEW

File: gqltesting/testing.go [hunk 1]
```diff
@@ -23,6 +23,7 @@ type Test struct {
 	Variables      map[string]interface{}
 	ExpectedResult string
 	ExpectedErrors []*errors.QueryError
+	RawResponse    bool
```
Comment (pavelnikolov) [inline gqltesting/testing.go:26]: That's a nice addition!

**Comment by pavelnikolov** [comment]
Thank you for your contribution!

**Comment by eko** [comment]
@pavelnikolov I take this opportunity: do you think you could make tags to have a better management of the releases?

**Comment by pavelnikolov** [comment]
Yes, this is something I have been planing to do for some time. I expect to make it happen really soon. I'll also add a CHANGELOG.md file. Thank you for your patience.

**Comment by eko** [comment]
Great, thanks!

File: gqltesting/testing.go [hunk 2]
```diff
@@ -57,10 +58,22 @@ func RunTest(t *testing.T, test *Test) {
...
+		got = value
+	} else {
+		value, err := formatJSON(result.Data)
+		if err != nil {
+			t.Fatalf("got: invalid JSON: %s", err)
+		}
+		got = value
 	}
+
 	want, err := formatJSON([]byte(test.ExpectedResult))
```
Comment (pavelnikolov) [inline gqltesting/testing.go:77]: If raw response is used, do we need to leave the expected result raw as well?

Comment (pavelnikolov) [reply gqltesting/testing.go:77]: @eko ?

Comment (eko) [reply gqltesting/testing.go:77]: Yes because the `RawResponse` only acts on `got` variable (effective response), not on the `want` (expected result) specified: in unit tests you have to specify a raw (not formatted) expected response.

Maybe the `formatJSON()` is not necessary anymore and we could just `json.Marshal()`
